### ISSUE TITLE
Cannot read property 'indexOf' of null - _VisBuilder

### ISSUE THREAD

**Issue by tiagosiebler** [mstr-dev/Visualization-Plugins#89]
That pops up when using the current _VisBuilder plugin from here with 10.1 on TomCat:

![screen shot 2015-11-05 at 11 01 27 am](https://cloud.githubusercontent.com/assets/14090872/10966620/acb77b68-83ac-11e5-88c6-d16d397dd954.png)

**Comment by ffniu** [comment]
This error was caused by Line 97 in VisbuilderCustomVisBase.js. As below:
        if (path !== "") {
            content = mstrmojo.loadFileSync(path);
            if (content && content.indexOf("<html>") !== -1) {
                //if global.css is missing content will contain a 404 page, so we need to clear it
                content = '';
            }

As mstrmojo has renamed loadFile() to loadFileSync() in 10.2, we changed this line code to adapt to 10.2, while which is not compatible with 10.1.

Later, after adding version number to visualization builder, we may branch out to avoid this case.

**Comment by ckiefer** [comment]
I was just checking the MSTR download site. 10.2 is not available yet. Why is the public code adapted to a version not available yet?

**Comment by batkru** [comment]
Hello, thanks for the feedback! You can download the latest commit we posted which works again with 10.1. We apologize for the inconvenience this may have caused. Also, we're working now on implementing an internal process so that this can be prevented in the future. Thanks!

**Comment by ckiefer** [comment]
Hi
There's still an error when opening a visualization using the latest _VisBuilder plug-in:
mstrmojo.loadFile is not a function

![image](https://cloud.githubusercontent.com/assets/8458235/11162315/af9c91c8-8a9c-11e5-99f1-e9fa385c46fd.png)

**Comment by PeipeiChen** [comment]
Hi, please have a try with latest commit we posted. It should be working well on both 10.1 and 10.2.

**Comment by ckiefer** [comment]
Hi
Yes, the latest plug-in works. Thanks for the support.
